- name: Slå på persistent journald-logging
  lineinfile:
    path: /etc/systemd/journald.conf
    regexp: "^#?Storage="
    line: "Storage=persistent"

- name: Begrens journald-plass
  lineinfile:
    path: /etc/systemd/journald.conf
    regexp: "^#?SystemMaxUse="
    line: "SystemMaxUse=200M"

- name: Restart journald
  service:
    name: systemd-journald
    state: restarted

- name: Installer logrotate
  apt:
    name: logrotate
    state: present

- name: Installer acct for kommandohistorikk
  apt:
    name: acct
    state: present

- name: Start acct-logging
  command: /usr/sbin/accton /var/log/account/pacct
  args:
    creates: /var/log/account/pacct
