- name: Ta vekk root SSH login
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^PermitRootLogin"
    line: "PermitRootLogin no"
  notify: Restart SSH

- name: Deaktiver passord-innlogging i SSH
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication"
    line: "PasswordAuthentication no"
  notify: Restart SSH

- name: Deaktiver ChallengeResponseAuthentication
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^ChallengeResponseAuthentication"
    line: "ChallengeResponseAuthentication no"
  notify: Restart SSH

- name: Begrens SSH-innlogging til 'ansible'-bruker
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^AllowUsers"
    line: "AllowUsers ansible"
  notify: Restart SSH
